### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by dimakravets603**

### CODE REVIEW

**Review by KonstKh — APPROVED** [review]

**Comment by KonstKh** [comment]
ok, you can merge this PR to develop and start with the second task. Please, don't copy-paste some code from internet, I'm absolut not interesting of review it, make yours.

**Comment by KonstKh** [comment]
It's actually smth wrong again - your PR is in the "closed" state. Try to change it first, than merge it to develop.

**Comment by dimakravets603** [comment]
W

**Comment by dimakravets603** [comment]
Hello Konstantin, sorry for not answering for so long. I changed the pull
request and made a todo list
dimakravets603/TODO (github.com) <https://github.com/dimakravets603/TODO>

сб, 2 окт. 2021 г. в 20:35, KonstKh ***@***.***>:

**Pull request merged**
